package ips2023pl21.service;

public enum State {
	SUCCESS,
	EMPLEADONULL,
	HORARIONULL,
	INICIOAFTERFIN,
	NOSEMANADEANTELACION,
	SOLAPAFRANJAS,
	OVERDAILYMAX,
	OVERWEEKLYMAX,
	CONCURRENCEERROR,
	INSTALACIONNULL,
	JARDINERONULL,
	INTERFIEREENTRENAMIENTO,
	LOGINFAIL_USERNOTFOUND,
	LOGINFAIL_USERNOTALLOWED,
	EQUIPONULL
}
