package ips2023pl21.service;

public enum State {
	SUCCESS,
	EMPLEADONULL,
	MEDIONULL,
	HORARIONULL,
	INICIOAFTERFIN,
	NOSEMANADEANTELACION,
	SOLAPAFRANJAS,
	OVERDAILYMAX,
	OVERWEEKLYMAX,
	DBERROR,
	INSTALACIONNULL,
	JARDINERONULL,
	INTERFIEREENTRENAMIENTO,
	LOGINFAIL_USERNOTFOUND,
	LOGINFAIL_USERNOTALLOWED,
	EQUIPONULL,
	UNKNOWN,
	ENCRYPTION_ERROR
}
